---
title: Kevin Suttle
tagline: Design Technologist. Slab serif T-shape.
url: http://kevinsuttle.com
permalink: "/posts/:title"
timezone: America/New_York
exclude:
- CNAME
- README.md
- node_modules
- bower_components
- gulpfile.js
- package.json
defaults:
- scope:
    path: ''
    type: posts
  values:
    layout: post
