name: Kevin Suttle
tagline: Designer. Developer. Writer. Presenter.
url: kevinsuttle.com
permalink: /posts/:title
markdown: kramdown
timezone: America/New_York
exclude: ["CNAME", "README.md", "node_modules", "bower_components", "gulpfile.js", "package.json"]
